# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DO NOT MOVE\My Documents\GitHub\LMMS-Theme-Installer\ui\ui\firstrunwizard.ui'
#
# Created: Sat Dec 08 19:34:31 2012
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FirstRunWizard(object):
    def setupUi(self, FirstRunWizard):
        FirstRunWizard.setObjectName("FirstRunWizard")
        FirstRunWizard.setWindowModality(QtCore.Qt.ApplicationModal)
        FirstRunWizard.resize(412, 294)
        self.introWizardPage = QtGui.QWizardPage()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.introWizardPage.sizePolicy().hasHeightForWidth())
        self.introWizardPage.setSizePolicy(sizePolicy)
        self.introWizardPage.setObjectName("introWizardPage")
        self.gridLayout_2 = QtGui.QGridLayout(self.introWizardPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.introLabel = QtGui.QLabel(self.introWizardPage)
        self.introLabel.setObjectName("introLabel")
        self.gridLayout_2.addWidget(self.introLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        FirstRunWizard.addPage(self.introWizardPage)
        self.optionsWizardPage1 = QtGui.QWizardPage()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsWizardPage1.sizePolicy().hasHeightForWidth())
        self.optionsWizardPage1.setSizePolicy(sizePolicy)
        self.optionsWizardPage1.setSubTitle("")
        self.optionsWizardPage1.setObjectName("optionsWizardPage1")
        self.gridLayout = QtGui.QGridLayout(self.optionsWizardPage1)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.themeDirLabel = QtGui.QLabel(self.optionsWizardPage1)
        self.themeDirLabel.setObjectName("themeDirLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.themeDirLabel)
        self.themeDirLineEdit = QtGui.QLineEdit(self.optionsWizardPage1)
        self.themeDirLineEdit.setObjectName("themeDirLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.themeDirLineEdit)
        self.themeDirHelpLabel = QtGui.QLabel(self.optionsWizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themeDirHelpLabel.sizePolicy().hasHeightForWidth())
        self.themeDirHelpLabel.setSizePolicy(sizePolicy)
        self.themeDirHelpLabel.setWordWrap(True)
        self.themeDirHelpLabel.setObjectName("themeDirHelpLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.themeDirHelpLabel)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        FirstRunWizard.addPage(self.optionsWizardPage1)
        self.finishWizardPage = QtGui.QWizardPage()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finishWizardPage.sizePolicy().hasHeightForWidth())
        self.finishWizardPage.setSizePolicy(sizePolicy)
        self.finishWizardPage.setObjectName("finishWizardPage")
        self.gridLayout_3 = QtGui.QGridLayout(self.finishWizardPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.finishLabel = QtGui.QLabel(self.finishWizardPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finishLabel.sizePolicy().hasHeightForWidth())
        self.finishLabel.setSizePolicy(sizePolicy)
        self.finishLabel.setWordWrap(True)
        self.finishLabel.setObjectName("finishLabel")
        self.gridLayout_3.addWidget(self.finishLabel, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        FirstRunWizard.addPage(self.finishWizardPage)

        self.retranslateUi(FirstRunWizard)
        QtCore.QMetaObject.connectSlotsByName(FirstRunWizard)

    def retranslateUi(self, FirstRunWizard):
        FirstRunWizard.setWindowTitle(QtGui.QApplication.translate("FirstRunWizard", "Configuration Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.introWizardPage.setTitle(QtGui.QApplication.translate("FirstRunWizard", "Introduction", None, QtGui.QApplication.UnicodeUTF8))
        self.introLabel.setText(QtGui.QApplication.translate("FirstRunWizard", "This wizard will help you configure LMMS Theme Installer.", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsWizardPage1.setTitle(QtGui.QApplication.translate("FirstRunWizard", "General Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.themeDirLabel.setText(QtGui.QApplication.translate("FirstRunWizard", "Theme Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.themeDirHelpLabel.setText(QtGui.QApplication.translate("FirstRunWizard", "The generated directory may be wrong since it\'s based on the current theme directory.", None, QtGui.QApplication.UnicodeUTF8))
        self.finishWizardPage.setTitle(QtGui.QApplication.translate("FirstRunWizard", "Conclusion", None, QtGui.QApplication.UnicodeUTF8))
        self.finishLabel.setText(QtGui.QApplication.translate("FirstRunWizard", "LMMS Theme Installer is now configured.", None, QtGui.QApplication.UnicodeUTF8))

