# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DO NOT MOVE\My Documents\GitHub\LMMS-Theme-Installer\ui\ui\mainwindow.ui'
#
# Created: Sat Jan 19 23:46:52 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(675, 397)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.themeTab = QtGui.QWidget()
        self.themeTab.setEnabled(True)
        self.themeTab.setObjectName("themeTab")
        self.gridLayout = QtGui.QGridLayout(self.themeTab)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtGui.QFrame(self.themeTab)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.themeDescriptionWebView = QtWebKit.QWebView(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themeDescriptionWebView.sizePolicy().hasHeightForWidth())
        self.themeDescriptionWebView.setSizePolicy(sizePolicy)
        self.themeDescriptionWebView.setUrl(QtCore.QUrl("about:blank"))
        self.themeDescriptionWebView.setObjectName("themeDescriptionWebView")
        self.gridLayout_3.addWidget(self.themeDescriptionWebView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 2, 1, 1)
        self.themeListWidget = QtGui.QListWidget(self.themeTab)
        self.themeListWidget.setObjectName("themeListWidget")
        self.gridLayout.addWidget(self.themeListWidget, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 3)
        self.tabWidget.addTab(self.themeTab, "")
        self.presetTab = QtGui.QWidget()
        self.presetTab.setObjectName("presetTab")
        self.gridLayout_2 = QtGui.QGridLayout(self.presetTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.presetListWidget = QtGui.QListWidget(self.presetTab)
        self.presetListWidget.setObjectName("presetListWidget")
        self.gridLayout_2.addWidget(self.presetListWidget, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.presetTab)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.presetDescriptionWebView = QtWebKit.QWebView(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presetDescriptionWebView.sizePolicy().hasHeightForWidth())
        self.presetDescriptionWebView.setSizePolicy(sizePolicy)
        self.presetDescriptionWebView.setUrl(QtCore.QUrl("about:blank"))
        self.presetDescriptionWebView.setObjectName("presetDescriptionWebView")
        self.gridLayout_5.addWidget(self.presetDescriptionWebView, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.tabWidget.addTab(self.presetTab, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 675, 21))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtGui.QMenu(self.menuBar)
        self.menu_Edit.setEnabled(True)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setEnabled(False)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setEnabled(True)
        self.actionOptions.setObjectName("actionOptions")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu_File.addAction(self.actionExit)
        self.menu_Edit.addAction(self.actionOptions)
        self.menu_Help.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Edit.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "LMMS Theme Installer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.themeTab), QtGui.QApplication.translate("MainWindow", "Themes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.presetTab), QtGui.QApplication.translate("MainWindow", "Presets", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
